kevin_enquete_lister:
    path:     /
    defaults: { _controller: KevinEnqueteBundle:Question:lister }

kevin_enquete_ajouter:
    path:     /ajouter
    defaults: { _controller: KevinEnqueteBundle:Question:ajouter }

kevin_enquete_supprimer:
    path:     /supprimer
    defaults: { _controller: KevinEnqueteBundle:Question:supprimer }

kevin_enquete_modifier:
    path:     /modifier
    defaults: { _controller: KevinEnqueteBundle:Question:modifier }
